### ISSUE TITLE
Agenda Item: SSL Cert for Techlahoma.org

### ISSUE THREAD

**Issue by blazedd** [techlahoma/townhall#4]
I would like to propose that a SSL certificate be setup via traditional provider or Lets Encrypt for Techlahoma.org

I'd like to suggest that a SSL cert for your main website has become a standard for publishing websites, even when you're not sending personal information. Not to mention the Google ranking bonuses.

Also it's a little frustrating if you're coming from the donation site:
![9hxpvhf](https://cloud.githubusercontent.com/assets/93261/14745245/11332c16-0870-11e6-97ec-7c45a56a0ef7.gif)

**Comment by jagthedrummer** [comment]
As we currently host the lander on Gihub Pages, and as GH Pages does not allow SSL for custom domains doing this would mean that we need a new deployment strategy for the site. Not impossible, but not a non-trivial amount of effort. (Not arguing against this, just relaying info.)

**Comment by blazedd** [comment]
Speaking only from a perspective of Ease of use, Cloudflare would solve this with their free SSL certs that they provide, which seems to be the only solution to keep it in Github Pages.

That said, I really don't want to step on toes with the current DNS provider as they seem like they are invested back in Techlahoma.

**Comment by jagthedrummer** [comment]
Oh, yeah, we could probably stick CloudFront or some other CDN in front of it and hook up a cert without needing to switch DNS providers.

**Comment by blazedd** [comment]
Resolved as per https://blog.squarespace.com/blog/were-securing-millions-of-websites-with-ssl
